#!/bin/sh /etc/rc.common
# Copyright (C) 2021 Ashkan Jazayeri <ashkan@jazayeri.net>

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/suricata-update

validate_suricata_update_section() {
	uci_load_validate suricata-update suricata-update "$1" "$2" \
		'rulespath:string' \
		'defaultpath:string:/var/lib/suricata' \
		'reload_suricata:bool:1' \
		'enable_sources:bool:1' \
		'test_update:bool' \
		'update_source_list:bool:1'
}

enable_list() {
	suricata-update enable-source $1 -D $defaultpath
}

start_suricata_update() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	[ $update_source_list -eq "1" ] && \
		suricata-update update-sources -D $defaultpath
	[ $enable_sources -eq "1" ] && \
		config_list_foreach update sources enable_list

	procd_open_instance
	procd_set_param command $PROG -v
	[ $defaultpath ] && procd_append_param command -D $defaultpath
	[ $rulespath ] && procd_append_param command -o $rulespath
	[ $test_update = 0 ] && procd_append_param command --no-test
	[ $reload_suricata = 1 ] && procd_append_param command --reload-command "/etc/init.d/suricata reload"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	service_stop ${PROG}
}

start_service() {
	config_load suricata-update
	validate_suricata_update_section update start_suricata_update
}

service_triggers()
{
	procd_add_reload_trigger "suricata-update"
	procd_add_validation validate_suricata_update_section
}
